import tika
import tika.parser

file_extensions = {
    ".blend": {"File Type": "3D Modeling File", "Subtype": "Blender 3D File", "MIME Type": "application/x-blender"},
    ".max": {"File Type": "3D Modeling File", "Subtype": "3D Studio Max File", "MIME Type": "application/octet-stream"},
    ".mb": {"File Type": "3D Modeling File", "Subtype": "Autodesk Maya File", "MIME Type": "application/octet-stream"},
    ".fbx": {"File Type": "3D Modeling File", "Subtype": "FBX File", "MIME Type": "application/octet-stream"},
    ".obj": {"File Type": "3D Modeling File", "Subtype": "3D Object File", "MIME Type": "application/octet-stream"},
    ".stl": {"File Type": "3D Modeling File", "Subtype": "STL File", "MIME Type": "application/sla"},
    ".gltf": {"File Type": "3D Modeling File", "Subtype": "GLTF Model", "MIME Type": "model/gltf+json"},
    ".dae": {"File Type": "3D Modeling File", "Subtype": "3D Collada File", "MIME Type": "model/vnd.collada+xml"},
    ".tar": {"File Type": "Archive", "Subtype": "TAR Archive", "MIME Type": "application/x-tar"},
    ".ogg": {"File Type": "Audio Files", "Subtype": "OGG Audio", "MIME Type": "audio/ogg"},
    ".flac": {"File Type": "Audio Files", "Subtype": "FLAC Audio", "MIME Type": "audio/flac"},
    ".m4a": {"File Type": "Audio Files", "Subtype": "M4A Audio", "MIME Type": "audio/mp4"},
    ".midi": {"File Type": "Audio Files", "Subtype": "MIDI File", "MIME Type": "audio/midi"},
    ".aiff": {"File Type": "Audio Files", "Subtype": "AIFF Audio File", "MIME Type": "audio/x-aiff"},
    ".m4b": {"File Type": "Audio Files", "Subtype": "M4B Audiobook", "MIME Type": "audio/mp4"},
    ".bak": {"File Type": "Backup Files", "Subtype": "Backup File", "MIME Type": "application/octet-stream"},
    ".dwg": {"File Type": "CAD Files", "Subtype": "AutoCAD Drawing", "MIME Type": "application/acad"},
    ".dxf": {"File Type": "CAD Files", "Subtype": "DXF File", "MIME Type": "image/vnd.dxf"},
    ".step": {"File Type": "CAD Files", "Subtype": "STEP File", "MIME Type": "application/step"},
    ".iges": {"File Type": "CAD Files", "Subtype": "IGES File", "MIME Type": "application/iges"},
    ".crt": {"File Type": "Certificate and Keys", "Subtype": "SSL Certificate", "MIME Type": "application/x-x509-ca-cert"},
    ".pgp": {"File Type": "Certificate and Keys", "Subtype": "PGP Key", "MIME Type": "application/pgp-encrypted"},
    ".pem": {"File Type": "Certificate and Keys", "Subtype": "SSH Private Key", "MIME Type": "application/x-pem-file"},
    ".o": {"File Type": "Compiled Files", "Subtype": "Object File", "MIME Type": "application/x-object"},
    ".so": {"File Type": "Compiled Files", "Subtype": "Shared Object (Linux)", "MIME Type": "application/x-sharedlib"},
    ".class": {"File Type": "Compiled Files", "Subtype": "Java Bytecode", "MIME Type": "application/java-vm"},
    ".pyc": {"File Type": "Compiled Files", "Subtype": "Python Bytecode", "MIME Type": "application/x-python-code"},
    ".zip": {"File Type": "Compressed Files", "Subtype": "ZIP Archive", "MIME Type": "application/zip"},
    ".rar": {"File Type": "Compressed Files", "Subtype": "RAR Archive", "MIME Type": "application/x-rar-compressed"},
    ".7z": {"File Type": "Compressed Files", "Subtype": "7-Zip Archive", "MIME Type": "application/x-7z-compressed"},
    ".bz2": {"File Type": "Compressed Files", "Subtype": "BZIP2 Archive", "MIME Type": "application/x-bzip2"},
    ".gz": {"File Type": "Compressed Files", "Subtype": "GZIP Archive", "MIME Type": "application/gzip"},
    ".tf": {"File Type": "Configuration Files", "Subtype": "Terraform Configuration", "MIME Type": "text/plain"},
    ".json": {"File Type": "Configuration Files", "Subtype": "JSON", "MIME Type": "application/json"},
    ".yaml": {"File Type": "Configuration Files", "Subtype": "YAML", "MIME Type": "application/x-yaml"},
    ".xml": {"File Type": "Configuration Files", "Subtype": "XML", "MIME Type": "application/xml"},
    ".ini": {"File Type": "Configuration Files", "Subtype": "INI", "MIME Type": "text/plain"},
    ".properties": {"File Type": "Configuration Files", "Subtype": "Properties", "MIME Type": "text/plain"},
    ".toml": {"File Type": "Configuration Files", "Subtype": "TOML", "MIME Type": "text/plain"},
    ".env": {"File Type": "Configuration Files", "Subtype": "ENV File", "MIME Type": "text/plain"},
    ".yml": {"File Type": "Configuration Files", "Subtype": "YAML File", "MIME Type": "application/x-yaml"},
    ".csv": {"File Type": "Data Files", "Subtype": "CSV File", "MIME Type": "text/csv"},
    ".parquet": {"File Type": "Data Files", "Subtype": "Parquet File", "MIME Type": "application/octet-stream"},
    ".sas7bdat" : {"File Type" : "Data Files" , "Subtype" : "SAS File", "MIME Type" : "application/x-sas-data"},
    ".avro": {"File Type": "Data Files", "Subtype": "AVRO File", "MIME Type": "application/octet-stream"},
    ".avsc": {"File Type": "Data Files", "Subtype": "AVRO File", "MIME Type": "text/plain"},
    ".avdl": {"File Type": "Data Files", "Subtype": "AVRO File", "MIME Type": "text/plain"},
    ".orc": {"File Type": "Data Files", "Subtype": "ORC File", "MIME Type": "application/octet-stream"},
    ".xlsb": {"File Type": "Data Files", "Subtype": "Excel Binary Workbook", "MIME Type": "application/vnd.ms-excel.sheet.binary.macroenabled.12"},
    ".psd": {"File Type": "Design Files", "Subtype": "Photoshop PSD File", "MIME Type": "image/vnd.adobe.photoshop"},
    ".ai": {"File Type": "Design Files", "Subtype": "Adobe Illustrator File", "MIME Type": "application/postscript"},
    ".sketch": {"File Type": "Design Files", "Subtype": "Sketch File", "MIME Type": "application/octet-stream"},
    ".fig": {"File Type": "Design Files", "Subtype": "Figma Design File", "MIME Type": "application/octet-stream"},
    ".cdr": {"File Type": "Design Files", "Subtype": "CorelDRAW File", "MIME Type": "application/x-coreldraw"},
    ".xcf": {"File Type": "Design Files", "Subtype": "GIMP File", "MIME Type": "application/x-gimp"},
    ".iso": {"File Type": "Disk Image Files", "Subtype": "ISO Disk Image", "MIME Type": "application/x-iso9660-image"},
    ".bin": {"File Type": "Disk Image Files", "Subtype": "Bin/Cue Disk Image", "MIME Type": "application/octet-stream"},
    ".dmg": {"File Type": "Disk Image Files", "Subtype": "DMG Disk Image", "MIME Type": "application/x-apple-diskimage"},
    ".vhd": {"File Type": "Disk Image Files", "Subtype": "VHD Disk Image", "MIME Type": "application/octet-stream"},
    ".epub": {"File Type": "Document Files", "Subtype": "ePub eBook", "MIME Type": "application/epub+zip"},
    ".mobi": {"File Type": "Document Files", "Subtype": "Mobipocket eBook", "MIME Type": "application/x-mobipocket-ebook"},
    ".djvu": {"File Type": "Document Files", "Subtype": "DjVu File", "MIME Type": "image/vnd.djvu"},
    ".cbr": {"File Type": "Document Files", "Subtype": "Comic Book Archive", "MIME Type": "application/x-cbr"},
    ".tex": {"File Type": "Document Files", "Subtype": "LaTeX Source File", "MIME Type": "application/x-tex"},
    ".pst": {"File Type": "Email Files", "Subtype": "Outlook PST", "MIME Type": "application/vnd.ms-outlook"},
    ".ost": {"File Type": "Email Files", "Subtype": "Outlook OST", "MIME Type": "application/vnd.ms-outlook"},
    ".eml": {"File Type": "Email Files", "Subtype": "MIME Email", "MIME Type": "message/rfc822"},
    ".mbox": {"File Type": "Email Files", "Subtype": "MBOX Email", "MIME Type": "application/mbox"},
    ".gpg": {"File Type": "Encrypted Files", "Subtype": "GPG Encrypted File", "MIME Type": "application/pgp-encrypted"},
    ".enc": {"File Type": "Encrypted Files", "Subtype": "Encrypted File", "MIME Type": "application/octet-stream"},
    ".msi": {"File Type": "Executable Files", "Subtype": "Windows Executable File", "MIME Type": "application/x-msi"},
    ".exe": {"File Type": "Executable Files", "Subtype": "Windows Executable", "MIME Type": "application/x-msdownload"},
    ".out": {"File Type": "Executable Files", "Subtype": "Linux Executable", "MIME Type": "application/octet-stream"},
    ".elf": {"File Type": "Executable Files", "Subtype": "ELF Executable", "MIME Type": "application/x-executable"},
    ".bat": {"File Type": "Executable Files", "Subtype": "Windows Batch File", "MIME Type": "application/x-bat"},
    ".cmd": {"File Type": "Executable Files", "Subtype": "Windows Command Script", "MIME Type": "application/x-msdos-program"},
    ".ps1": {"File Type": "Executable Files", "Subtype": "PowerShell Script", "MIME Type": "application/x-powershell"},
    ".qbb": {"File Type": "Financial Data Files", "Subtype": "QuickBooks Backup", "MIME Type": "application/vnd.intu.qbo"},
    ".qbw": {"File Type": "Financial Data Files", "Subtype": "QuickBooks Company File", "MIME Type": "application/vnd.intu.qbo"},
    ".ttf": {"File Type": "Font Files", "Subtype": "TrueType Font", "MIME Type": "font/ttf"},
    ".otf": {"File Type": "Font Files", "Subtype": "OpenType Font", "MIME Type": "font/otf"},
    ".woff": {"File Type": "Font Files", "Subtype": "WOFF Font", "MIME Type": "font/woff"},
    ".woff2": {"File Type": "Font Files", "Subtype": "WOFF2 Font", "MIME Type": "font/woff2"},
    ".eot": {"File Type": "Font Files", "Subtype": "EOT Font File", "MIME Type": "application/vnd.ms-fontobject"},
    ".rom": {"File Type": "Game Files", "Subtype": "ROM File", "MIME Type": "application/octet-stream"},
    ".sav": {"File Type": "Game Files", "Subtype": "Game Save File", "MIME Type": "application/octet-stream"},
    ".gba": {"File Type": "Game Files", "Subtype": "Game Boy Advance ROM", "MIME Type": "application/octet-stream"},
    ".nds": {"File Type": "Game Files", "Subtype": "Nintendo DS ROM", "MIME Type": "application/octet-stream"},
    ".shp": {"File Type": "Geospatial Files", "Subtype": "Shapefile", "MIME Type": "application/octet-stream"},
    ".geojson": {"File Type": "Geospatial Files", "Subtype": "GeoJSON", "MIME Type": "application/json"},
    ".kml": {"File Type": "Geospatial Files", "Subtype": "KML File", "MIME Type": "application/vnd.google-earth.kml+xml"},
    ".gpx": {"File Type": "Geospatial Files", "Subtype": "GPX File", "MIME Type": "application/gpx+xml"},
    ".gif": {"File Type": "Image File", "Subtype": "GIF Image", "MIME Type": "image/gif"},
    ".bmp": {"File Type": "Image File", "Subtype": "BMP Image", "MIME Type": "image/bmp"},
    ".tiff": {"File Type": "Image File", "Subtype": "TIFF Image", "MIME Type": "image/tiff"},
    ".jpeg": {"File Type": "Image File", "Subtype": "JPEG Image", "MIME Type": "image/jpeg"},
    ".png": {"File Type": "Image File", "Subtype": "PNG Image", "MIME Type": "image/png"},
    ".ico": {"File Type": "Image File", "Subtype": "Icon File", "MIME Type": "image/x-icon"},
    ".svg": {"File Type": "Image File", "Subtype": "Scalable Vector Graphic", "MIME Type": "image/svg+xml"},
    ".eps": {"File Type": "Image File", "Subtype": "Encapsulated PostScript", "MIME Type": "application/postscript"},
    ".log": {"File Type": "Log Files", "Subtype": "Log File", "MIME Type": "text/plain"},
    ".syslog": {"File Type": "Log Files", "Subtype": "System Log", "MIME Type": "text/plain"},
    ".evtx": {"File Type": "Log Files", "Subtype": "Windows Event Log", "MIME Type": "application/octet-stream"},
    ".perf": {"File Type": "Log Files", "Subtype": "Performance Log", "MIME Type": "text/plain"},
    ".dcm": {"File Type": "Medical Files", "Subtype": "DICOM Image", "MIME Type": "application/dicom"},
    ".nii": {"File Type": "Medical Files", "Subtype": "NIfTI Image", "MIME Type": "application/nifti"},
    ".hdr": {"File Type": "Medical Files", "Subtype": "Analyze 7.5", "MIME Type": "application/octet-stream"},
    ".vmr": {"File Type": "Medical Files", "Subtype": "BrainVoyager File", "MIME Type": "application/octet-stream"},
    ".audit": {"File Type": "Monitoring Files", "Subtype": "Audit File", "MIME Type": "text/plain"},
    ".mib": {"File Type": "Monitoring Files", "Subtype": "SNMP MIB File", "MIME Type": "text/plain"},
    ".docx": {"File Type": "MS Office Documents", "Subtype": "Word Document", "MIME Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
    ".xlsx": {"File Type": "MS Office Documents", "Subtype": "Excel Spreadsheet", "MIME Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
    ".pptx": {"File Type": "MS Office Documents", "Subtype": "PowerPoint Presentation", "MIME Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
    ".mdb": {"File Type": "MS Office Documents", "Subtype": "Access Database", "MIME Type": "application/vnd.ms-access"},
    ".vsdx": {"File Type": "MS Office Documents", "Subtype": "Visio Diagram", "MIME Type": "application/vnd.visio"},
    ".jpg": {"File Type": "Multimedia Files", "Subtype": "JPEG Image", "MIME Type": "image/jpeg"},
    ".mp4": {"File Type": "Multimedia Files", "Subtype": "MP4 Video", "MIME Type": "video/mp4"},
    ".wav": {"File Type": "Multimedia Files", "Subtype": "WAV Audio", "MIME Type": "audio/wav"},
    ".mp3": {"File Type": "Multimedia Files", "Subtype": "MP3 Audio", "MIME Type": "audio/mpeg"},
    ".avi": {"File Type": "Multimedia Files", "Subtype": "AVI Video", "MIME Type": "video/x-msvideo"},
    ".mkv": {"File Type": "Multimedia Files", "Subtype": "MKV Video", "MIME Type": "video/x-matroska"},
    ".pdf": {"File Type": "PDF", "Subtype": "PDF", "MIME Type": "application/pdf"},
    ".webp": {"File Type": "Image File", "Subtype": "WebP Image", "MIME Type": "image/webp"},
    ".h5": {"File Type": "Scientific Data Files", "Subtype": "HDF5 File", "MIME Type": "application/x-hdf5"},
    ".nc": {"File Type": "Scientific Data Files", "Subtype": "NetCDF File", "MIME Type": "application/x-netcdf"},
    ".grib": {"File Type": "Scientific Data Files", "Subtype": "GRIB File", "MIME Type": "application/x-grib"},
    ".mat": {"File Type": "Scientific Data Files", "Subtype": "MAT File (MATLAB)", "MIME Type": "application/x-matlab-data"},
    ".jks": {"File Type": "Security Files", "Subtype": "Key Store", "MIME Type": "application/x-java-keystore"},
    ".pfx": {"File Type": "Security Files", "Subtype": "PKCS12 Certificate", "MIME Type": "application/x-pkcs12"},
    ".asc": {"File Type": "Security Files", "Subtype": "PGP Private Key", "MIME Type": "application/pgp-encrypted"},
    ".sig": {"File Type": "Security Files", "Subtype": "PGP Signature", "MIME Type": "application/pgp-signature"},
    ".crl": {"File Type": "Security Files", "Subtype": "Certificate Revocation List", "MIME Type": "application/pkix-crl"},
    ".cer": {"File Type": "Security Files", "Subtype": "X.509 Certificate", "MIME Type": "application/pkix-cert"},
    ".der": {"File Type": "Security Files", "Subtype": "DER Encoded Certificate", "MIME Type": "application/x-x509-ca-cert"},
    ".key": {"File Type": "Source Code", "Subtype": "Keynote Presentation", "MIME Type": "application/vnd.apple.keynote"},
    ".odp": {"File Type": "Source Code", "Subtype": "OpenDocument Presentation", "MIME Type": "application/vnd.oasis.opendocument.presentation"},
    ".php": {"File Type": "Source Code", "Subtype": "PHP Code", "MIME Type": "application/x-php"},
    ".rb": {"File Type": "Source Code", "Subtype": "Ruby Code", "MIME Type": "application/x-ruby"},
    ".swift": {"File Type": "Source Code", "Subtype": "Swift Code", "MIME Type": "application/x-swift"},
    ".kt": {"File Type": "Source Code", "Subtype": "Kotlin Code", "MIME Type": "application/x-kotlin"},
    ".rs": {"File Type": "Source Code", "Subtype": "Rust Code", "MIME Type": "text/x-rust"},
    ".dart": {"File Type": "Source Code", "Subtype": "Dart Code", "MIME Type": "application/x-dart"},
    ".pl": {"File Type": "Source Code", "Subtype": "Perl Script", "MIME Type": "text/x-perl"},
    ".r": {"File Type": "Source Code", "Subtype": "R Script", "MIME Type": "text/plain"},
    ".m": {"File Type": "Source Code", "Subtype": "MATLAB Script", "MIME Type": "text/x-matlab"},
    ".f": {"File Type": "Source Code", "Subtype": "FORTRAN Code", "MIME Type": "text/x-fortran"},
    ".cob": {"File Type": "Source Code", "Subtype": "COBOL Code", "MIME Type": "text/x-cobol"},
    ".hs": {"File Type": "Source Code", "Subtype": "Haskell Code", "MIME Type": "text/x-haskell"},
    ".lua": {"File Type": "Source Code", "Subtype": "Lua Code", "MIME Type": "text/x-lua"},
    ".scala": {"File Type": "Source Code", "Subtype": "Scala Code", "MIME Type": "text/x-scala"},
    ".ts": {"File Type": "Source Code", "Subtype": "TypeScript Code", "MIME Type": "application/x-typescript"},
    ".jl": {"File Type": "Source Code", "Subtype": "Julia Code", "MIME Type": "application/julia"},
    ".pas": {"File Type": "Source Code", "Subtype": "Pascal Code", "MIME Type": "text/x-pascal"},
    ".bash": {"File Type": "Source Code", "Subtype": "Bash Script", "MIME Type": "application/x-sh"},
    ".groovy": {"File Type": "Source Code", "Subtype": "Groovy Script", "MIME Type": "application/x-groovy"},
    ".py": {"File Type": "Source Code", "Subtype": "Python Code", "MIME Type": "text/x-python"},
    ".java": {"File Type": "Source Code", "Subtype": "Java Code", "MIME Type": "text/x-java-source"},
    ".c": {"File Type": "Source Code", "Subtype": "C Code", "MIME Type": "text/x-c"},
    ".cpp": {"File Type": "Source Code", "Subtype": "C++ Code", "MIME Type": "text/x-cpp"},
    ".h": {"File Type": "Source Code", "Subtype": "C Header File", "MIME Type": "text/x-chdr"},
    ".sh": {"File Type": "Source Code", "Subtype": "Shell Script", "MIME Type": "application/x-sh"},
    "Makefile": {"File Type": "Source Code", "Subtype": "Makefile", "MIME Type": "text/plain"},
    "Dockerfile": {"File Type": "Source Code", "Subtype": "Dockerfile", "MIME Type": "text/plain"},
    ".js": {"File Type": "Source Code", "Subtype": "JavaScript Code", "MIME Type": "application/javascript"},
    ".go": {"File Type": "Source Code", "Subtype": "Go Code", "MIME Type": "text/x-go"},
    ".jar": {"File Type": "Source Code Archives", "Subtype": "JAR File", "MIME Type": "application/java-archive"},
    ".war": {"File Type": "Source Code Archives", "Subtype": "WAR File", "MIME Type": "application/java-archive"},
    ".ear": {"File Type": "Source Code Archives", "Subtype": "EAR File", "MIME Type": "application/java-archive"},
    ".ods": {"File Type": "Spreadsheet Files", "Subtype": "OpenDocument Spreadsheet", "MIME Type": "application/vnd.oasis.opendocument.spreadsheet"},
    ".pgsql": {"File Type": "SQL and Database Files", "Subtype": "PostgreSQL Dump", "MIME Type": "application/sql"},
    ".dbf": {"File Type": "SQL and Database Files", "Subtype": "Oracle Database File", "MIME Type": "application/octet-stream"},
    ".sql": {"File Type": "SQL and Database Files", "Subtype": "SQL Script", "MIME Type": "application/sql"},
    ".sqlite": {"File Type": "SQL and Database Files", "Subtype": "SQLite Database", "MIME Type": "application/vnd.sqlite3"},
    ".dll": {"File Type": "System Files", "Subtype": "Windows DLL", "MIME Type": "application/vnd.microsoft.portable-executable"},
    ".ko": {"File Type": "System Files", "Subtype": "Linux Kernel Module", "MIME Type": "application/x-ko"},
    ".sys": {"File Type": "System Files", "Subtype": "Windows System File", "MIME Type": "application/x-msdownload"},
    ".init": {"File Type": "System Files", "Subtype": "Linux Init Script", "MIME Type": "text/plain"},
    ".reg": {"File Type": "System Files", "Subtype": "Windows Registry File", "MIME Type": "application/octet-stream"},
    ".lnk": {"File Type": "System Files", "Subtype": "Windows Shortcut", "MIME Type": "application/x-ms-shortcut"},
    ".apk": {"File Type": "System Files", "Subtype": "Android Package", "MIME Type": "application/vnd.android.package-archive"},
    ".ipa": {"File Type": "System Files", "Subtype": "iOS App Archive", "MIME Type": "application/octet-stream"},
    ".cab": {"File Type": "System Files", "Subtype": "Windows Cabinet File", "MIME Type": "application/vnd.ms-cab-compressed"},
    ".md": {"File Type": "Text Files", "Subtype": "Markdown File", "MIME Type": "text/markdown"},
    ".rtf": {"File Type": "Text Files", "Subtype": "Rich Text Format", "MIME Type": "application/rtf"},
    ".textile": {"File Type": "Text Files", "Subtype": "Textile File", "MIME Type": "text/x-textile"},
    ".svn": {"File Type": "Version Control Files", "Subtype": "Subversion Commit", "MIME Type": "application/x-subversion"},
    ".patch": {"File Type": "Version Control Files", "Subtype": "Git Patch", "MIME Type": "text/x-diff"},
    ".git": {"File Type": "Version Control Files", "Subtype": "Git Repository", "MIME Type": "application/x-git"},
    ".hg": {"File Type": "Version Control Files", "Subtype": "Mercurial Repository", "MIME Type": "application/x-mercurial"},
    ".gitignore": {"File Type": "Version Control Files", "Subtype": "Git Ignore File", "MIME Type": "text/plain"},
    ".gitattributes": {"File Type": "Version Control Files", "Subtype": "Git Attributes File", "MIME Type": "text/plain"},
    ".ova": {"File Type": "Virtualization Files", "Subtype": "OVA (Virtual Appliance)", "MIME Type": "application/x-virtualbox-ova"},
    ".qcow2": {"File Type": "Virtualization Files", "Subtype": "QCOW2 Disk Image", "MIME Type": "application/x-qcow2"},
    ".vdi": {"File Type": "Virtualization Files", "Subtype": "VirtualBox Disk Image", "MIME Type": "application/x-virtualbox-vdi"},
    ".vmdk": {"File Type": "Virtualization Files", "Subtype": "VMware Disk Image", "MIME Type": "application/x-vmdk"},
    ".vhdx": {"File Type": "Virtualization Files", "Subtype": "Hyper-V Disk Image", "MIME Type": "application/octet-stream"},
    ".html": {"File Type": "Web Files", "Subtype": "HTML File", "MIME Type": "text/html"},
    ".css": {"File Type": "Web Files", "Subtype": "CSS File", "MIME Type": "text/css"},
    ".js": {"File Type": "Web Files", "Subtype": "JavaScript File", "MIME Type": "application/javascript"},
    ".php": {"File Type": "Web Files", "Subtype": "PHP File", "MIME Type": "application/x-httpd-php"},
    ".aspx": {"File Type": "Web Files", "Subtype": "ASPX File", "MIME Type": "application/x-aspx"}
}

class Classifier:
    def classify(self, path):
        lst = path.split(".")
        file_ext = "." + str(lst[len(lst) - 1])
        if file_extensions[file_ext] is not None:
            return file_extensions[file_ext]
        else:
            parsed_file = tika.parser.from_file(path)
            return parsed_file['metadata']['Content-Type']